name: Terraform Apply on Commit

on:
  push:
    branches:
      - main  # Trigger only on commits to the main branch (you can adjust this)

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Replace with your Terraform version if different

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' # Conditional apply only on main branch
        run: terraform apply -auto-approve
