name: Terraform Apply on Commit
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "ASIA543FPMNOLMNS2QY6"
          aws-secret-access-key: "tzJ3UQ+/V6XbWkYStt8ILPqGVW+FSKnMfsTxLjTy"
          aws-region: us-east-1
        env:
          ACTIONS_STEP_DEBUG: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        
      # Network Folder Terraform Execution
      - name: Terraform Init in Network folder
        working-directory: ./Network
        run: terraform init
        
      - name: Terraform Plan in Network folder
        working-directory: ./Network
        run: terraform plan

      - name: Terraform Apply in Network folder
        working-directory: ./Network
        run: terraform apply -auto-approve

      # Webserver Folder Terraform Execution
      - name: Terraform Init in Webserver folder
        working-directory: ./Webserver
        run: terraform init

      - name: Terraform Plan in Webserver folder
        working-directory: ./Webserver
        run: terraform plan

      - name: Terraform Apply in Webserver folder
        working-directory: ./Webserver
        run: terraform apply -auto-approve
